

export const GET_JOB_ADVERTİSEMENT = "GET_JOB_ADVERTİSEMENT";

export const GET_ALL_CANDİDATES="GET_ALL_CANDİDATES"
export const GET_CANDİDATE_RESUME="GET_CANDİDATE_RESUME"
export const CANDİDATE_REGİSTER ="CANDİDATE_REGİSTER"


export const COMPANY_REGİSTER="COMPANY_REGİSTER"
export const GET_ALL_COMPANYS="GET_ALL_COMPANY"

export const GET_JOB_ADVERTİSEMENT_FİLTER_WORK_TYPES="GET_JOB_ADVERTİSEMENT_FİLTER_WORK_TYPES"
export const GET_JOB_ADVERTİSEMENT_FİLTER_WORK_PLACES="GET_JOB_ADVERTİSEMENT_FİLTER_WORK_PLACES"
export const GET_JOB_ADVERTİSEMENT_FİLTER_WORK_PLACES_AND_WORK_TYPE="GET_JOB_ADVERTİSEMENT_FİLTER_WORK_PLACES_AND_WORK_TYPE"
export const GET_WORK_TYPES="GET_WORK_TYPES"
export const GET_WORK_PLACES="GET_WORK_PLACE"
export const GET_JOB_POSİTİONS="GET_JOB_POSİTİONS"
export const GET_CİTİES="GET_CİTİES"


export const GET_EDUCATİONS ="GET_EDUCATİONS"
export const GET_EDUCATİON_GRADUATES="GET_EDUCATİON_GRADUATES"

export const GET_RESUME="GET_RESUME"

export const GET_EMPLOYEE_COMPANY_UPTADE_PROFİLE="GET_EMPLOYEE_COMPANY_UPTADE_PROFİLE"

export const GET_EMPLOYEE_CONFİRM_JOB_ADVERTİSEMENT_FALSE="GET_EMPLOYEE_CONFİRM_JOB_ADVERTİSEMENT_FALSE"


export const GET_RESUME_EDUCATİON_BY_İD="GET_RESUME_EDUCATİON_BY_İD"
export const GET_RESUME_LANGUAGE_BY_İD="GET_RESUME_LANGUAGE_BY_İD"


export const GET_RESUME_TECHONOLOGY_BY_İD="GET_RESUME_TECHONOLOGY_BY_İD"
export const GET_RESUME_JOBEXPERİENCE_BY_İD="GET_RESUME_JOBEXPERİENCE_BY_İD"

export const GET_JOB_ADVERTİSEMENT_FAVORİTE="GET_JOB_ADVERTİSEMENT_FAVORİTE"
